name: Code Lint and Test

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main', 'dev']

jobs:
  lint:
    name: â¬£ ESLint, Ê¦ TypeScript, ğŸ’… Prettier, âœ… Cypress
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: â” Setup node
        uses: actions/setup-node@802632921f8532d2409ae6eac3313b6f81f11122
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
          version: 10
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: ğŸ”¬ Lint
        run: pnpm lint:strict

      - name: ğŸ” Type check
        run: pnpm typecheck

      - name: ğŸ’… Prettier check
        run: pnpm format:check

      # - name: Install Cypress binary
      #   run: npx cypress install

      # - name: âœ… Cypress tests
      #   uses: cypress-io/github-action@1b70233146622b69e789ccdd4f9452adc638d25a
      #   with:
      #     browser: chrome
      #     build: pnpm build
      #     component: true
      #     start: pnpm start
      #     wait-on: 'http://localhost:3000'
